### PR TITLE
Hotfix/cleanup unused variables

### PR DESCRIPTION
**Pull request by tirjok**
This fix contains some refactoring of controllers. Cleanup: remove unused variables from controllers

### CODE REVIEW

**Comment by unicodeveloper** [comment]
This is great!. One more thing I can't see the language files that the `trans` method calls. @tirjok You didn't add them?

**Comment by tirjok** [comment]
I missed it to add. Sorry for that.

**Comment by unicodeveloper** [comment]
What's your twitter handle @tirjok ? I should give you a shoutout on Twitter 😄

**Comment by tirjok** [comment]
Yes :) Sure please.

**Comment by unicodeveloper** [comment]
What's your twitter username?

**Comment by tirjok** [comment]
Abu Baker Siddique (@abskomol)

**Pull request merged**
